apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: cached-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-app
          image: palolaur/todo-app:1.12
          env:
            - name: PORT
              value: "3002"
            - name: IMAGE_STORAGE
              value: "/app/files"
          volumeMounts:
            - name: cached-image
              mountPath: /app/files
